name: TurtleBot GUI Simulation (Live GUI)

on:
  workflow_dispatch:

jobs:
  turtlebot_sim:
    runs-on: ubuntu-22.04

    env:
      DISPLAY: :99

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install ROS 2 Humble manually
      run: |
        sudo apt update && sudo apt install -y curl gnupg2 lsb-release
        sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" | \
          sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
        sudo apt update
        sudo apt install -y ros-humble-desktop python3-colcon-common-extensions
        echo "source /opt/ros/humble/setup.bash" >> ~/.bashrc
        source /opt/ros/humble/setup.bash

    - name: Install simulation and GUI dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          ros-humble-turtlebot3-gazebo \
          xvfb x11vnc novnc websockify \
          git curl net-tools

    - name: Start virtual display
      run: |
        Xvfb :99 -screen 0 1920x1080x24 &
        sleep 3

    - name: Start VNC server
      run: |
        x11vnc -display :99 -nopw -forever -bg

    - name: Start noVNC
      run: |
        git clone https://github.com/novnc/noVNC.git
        cd noVNC
        ./utils/launch.sh --vnc localhost:5900 &

    - name: Launch tunnel to expose noVNC (public URL)
      run: |
        curl -s https://raw.githubusercontent.com/anderspitman/localhost.run/main/localhost.run.sh | bash
        echo "🌐 Access the TurtleBot GUI at the URL above (wait ~30s for Gazebo to load)"

    - name: Launch TurtleBot3 in Gazebo
      run: |
        export TURTLEBOT3_MODEL=burger
        source /opt/ros/humble/setup.bash
        ros2 launch turtlebot3_gazebo turtlebot3_world.launch.py
