name: TurtleBot GUI Simulation

on:
  workflow_dispatch:

jobs:
  turtlebot_sim:
    runs-on:  ubuntu-22.04

    env:
      DISPLAY: :99

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install ROS 2 Humble manually
      run: |
        sudo apt update && sudo apt install -y curl gnupg2 lsb-release
        sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" | \
          sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
        sudo apt update
        sudo apt install -y ros-humble-desktop python3-colcon-common-extensions
        echo "source /opt/ros/humble/setup.bash" >> ~/.bashrc
        source /opt/ros/humble/setup.bash

    - name: Install simulation dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          ros-humble-turtlebot3-gazebo \
          xvfb ffmpeg

    - name: Start virtual display
      run: |
        Xvfb :99 -screen 0 1920x1080x24 &
        sleep 3

    - name: Launch TurtleBot3 Gazebo and record
      run: |
        export TURTLEBOT3_MODEL=burger
        source /opt/ros/humble/setup.bash

        # Start recording display
        ffmpeg -video_size 1920x1080 -framerate 25 -f x11grab -i :99 \
               -t 30 -y gazebo_output.mp4 &
        FF_PID=$!

        # Launch Gazebo
        ros2 launch turtlebot3_gazebo turtlebot3_world.launch.py &
        ROS_PID=$!

        # Let it run for 30 seconds
        sleep 30
        kill $ROS_PID || true
        wait $FF_PID || true

    - name: Upload video artifact
      uses: actions/upload-artifact@v4
      with:
        name: turtlebot-gazebo
        path: gazebo_output.mp4
